<a href="https://colab.research.google.com/github/ehho34/PyTorch/blob/main/02_%ED%8C%8C%EC%9D%B4%ED%86%A0%EC%B9%98_%EA%B8%B0%EC%B4%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**02.파이토치 기초**

차원이 없는 것 - 스칼라
1차원 - 벡터
2차원 - 행렬(matrix)
3차원 - 텐서(tensor)
그 이상 - 다차원 행렬(배열)로 간주 가능 

## **02-텐서 조작하기**

### **Numpy로 텐서 만들기**

In [ ]:
import numpy as np

In [ ]:
#1차원 텐서인 벡터 만들기
t1=np.array([0., 1., 2., 3., 4., 5., 6.])
#파이썬에서는 list 생성 후 np.array로 1차원 array로 변환함
print(t1)

[0. 1. 2. 3. 4. 5. 6.]


In [ ]:
print('Rank of t1:', t1.ndim)  #ndim은 몇 차원인지 출력함
print('Shape of 1t:', t1.shape)  #shape는 크기를 출력함 (1XN)의 크기를 가지는 벡터라는 것을 표현해줌 ex-Shape of t: (7,)는 1X7의 크기를 가지는 벡터라는 뜻
                               #텐서의 크기는 ,(컴마)를 쓰기도 하고 X(곱하기를 쓰기도 함) 위의 예시는 1이 생략된 것이지만, 2행 3열의 2D텐서일 경우 (2X3)과 (2,3) 모두 가능

Rank of t1: 1
Shape of 1t: (7,)


In [ ]:
#각 벡터의 원소에 접근하는 방법

#인덱스를 통한 원소 접근
print('t1[0] t1[1] 1t[-1] = ', t1[0], t1[1], t1[-1])

#범위 지정으로 불러오기(Slicing)
print('t1[2:5] t1[4:-1]',t1[2:5], t1[4:-1]) #끝번호에 해당하는 건 포함X

#시작번호나 끝번호를 생략해서 불러오기
print('t1[:2] t1[3:]  = ',t1[:2],t1[3:])

t1[0] t1[1] 1t[-1] =  0.0 1.0 6.0
t1[2:5] t1[4:-1] [2. 3. 4.] [4. 5.]
t1[:2] t1[3:]  =  [0. 1.] [3. 4. 5. 6.]


In [ ]:
#2차원 행렬 만들기
t2=np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

tensor([1., 2.])


In [ ]:
print('Rank of t2: ', t2.ndim)
print('Shape of t2: ', t2.shape)

Rank of t2:  2
Shape of t2:  (4, 3)


### **파이토치 텐서 선언하기**

In [ ]:
import torch

In [ ]:
t3 = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t3)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [ ]:
print(t3.dim())   #rank(차원)을 보여주는 dim
print(t3.shape)   #shapel == size()  -> 크기를 보여줌 
print(t3.size())

1
torch.Size([7])
torch.Size([7])


In [ ]:
#인덱스로 접근 슬라이싱
print(t3[0], t3[1], t3[-1])  #인덱스
print(t3[2:5], t3[4:-1])  #슬라이싱
print(t3[:2], t3[3:])

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [ ]:
#2차원 텐서인 행렬 만들기
t4 = torch.FloatTensor([[1., 2., 3.],
                        [4., 5., 6.],
                        [7., 8., 9.],
                        [10., 11., 12.]])
print(t4)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [ ]:
print(t4.dim())
print(t4.size())
print(t4.shape)

2
torch.Size([4, 3])
torch.Size([4, 3])


In [ ]:
print(t4[:, 1])  #텐서에서 1번 인덱스 값을 모두 가져와라
print(t4[:,1] .size())

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


In [ ]:
print(t4[:, :-1])  #텐서에서 마지막에서 첫번째를 제외한 모든 값을 가져와라

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [ ]:
#브로드캐스팅(Broadcasting) : 크기가 다른 행렬 혹은 텐세에 대한 사칙 연산을 해야할 때 자동으로 크기를 맞춰서 수행하게 만드는 기능

#크기가 같은 때의 연산
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1+m2)

tensor([[5., 5.]])


In [ ]:
#크기가 다를 때의 연산
#Vector+scalar
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3])
print(m1+m2)
#▲m1의 크기는 (1,2)이고 m2의 크기는 (1,)임. 파이토치는 여기서 m2의 크기를 (1,2)로 변경하여 연산을 수행함.

tensor([[4., 5.]])


In [ ]:
#2X1Vector + 1X2Vecetor
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3],[4]])
print(m1+m2)
#▲파이토치가 두 벡터의 크기를 (2,2)로 변경하여 덧셈을 수행함

tensor([[4., 5.],
        [5., 6.]])


In [ ]:
#브로드캐스팅은 편리한 기능이지만, 나중에 원하는 결과가 나오지 않았을 때 오류의 발생지를 찾기 어렵기 때문에 주의해서 사용해야 함!

### **자주 사용되는 기능**

In [ ]:
#행렬 곱셉법 : 행렬 곱셉(.matual)과 원소별 곱셉(.mul)

In [ ]:
#matmul()
m1 =  torch.FloatTensor([[1,2], [3,4]])
m2 = torch.FloatTensor([[1],[2]])
print('Shape of Matrix 1: ',m1.shape)  #2X2
print('Shape of Matrix 2: ',m2.shape)   #1X2
print(m1.matmul(m2))  #2X1                #어.. 음.. 행렬을 모르겠어서 이해가 안되네..^^ ★질문해서 알아내기★

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [ ]:
#* 또는 mul() --> element-wise 곱셉(동일한 크기의 행렬이 동일한 위치에 있는 원소끼지 곱하는 것)
m1 = torch.FloatTensor([[1,2], [3,4]])
m2 = torch.FloatTensor([[1],[2]])
print('Shape of Matrix 1: ', m1.shape)  #2X2
print('Shaple of Matrix2: '), m2.shape  #2X1
print(m1*m2)   #브로드캐스팅 되어서 m2의 크기가 2X2로 변환됨
print(m1.mul(m2))

Shape of Matrix 1:  torch.Size([2, 2])
Shaple of Matrix2: 
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [ ]:
#평균(Mean) 구하기
t = torch.FloatTensor([1,2])
print(t.mean())   #1과 2의 평균이 1,5가 나옴

tensor(1.5000)


In [ ]:
t5 = torch.FloatTensor([[1,2],[3,4]])
print(t5)
print(t5.mean())  #4개의 평균인 2.5가 나옴

tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)


In [ ]:
print(t5.mean(dim=0))  #dim=0  ==  행렬에서 첫번째 차원  == '행'  --> dim을 인자로 주면 해당 차원을 제거한다는 의미 --> '열'민 남기겠다   // 그러니까 얘는 1과 3의 평균 & 2외 4의 평균


tensor([2., 3.])


In [ ]:
print(t5.mean(dim=1))  #dim=1  == 행렬에서 두번째 차원을 제거  == 열이 제거된 텐서   // 그러니까 얘는 1과 2의 평균 & 3과 4의 평균

tensor([1.5000, 3.5000])


In [ ]:
print(t5.mean(dim=-1))  #dim=-1   ==  행렬에서 마지막 차원을 제거한다는 의미 == 열의 차원을 제게

tensor([1.5000, 3.5000])


In [ ]:
#덧셈
t6 = torch.FloatTensor([[1,2],[3,4]])
print(t6) 

tensor([[1., 2.],
        [3., 4.]])


In [ ]:
print(t6.sum())  #단순한 원소 전체 덧셈
print(t6.sum(dim=0))  #행 제거
print(t6.sum(dim=1))  #열 제거
print(t6.sum(dim=-1)) #열 제거

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [ ]:
#최대(max) : 원소의 최대값 리턴 & 아그맥스(ArgMax) : 최대값을 가진 인덱스 리턴
t7 = torch.FloatTensor([[1,2], [3,4]])
print(t7)

tensor([[1., 2.],
        [3., 4.]])


In [ ]:
print(t7.max())  #Return onw value: max

tensor(4.)


In [ ]:
print(t7.max(dim=0))  #max에 dim 인자를 주면 argmax도 함께 리턴하는 특징이 있다.

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [ ]:
"""
▲[1,1]이 무슨 의미일까?
[[1,2],
 [3,4]]
 그러니까 3이랑 4의 인덱스는 [1,1]이다! 이런 뜻이야~
 """

'\n▲[1,1]이 무슨 의미일까?\n[[1,2],\n [3,4]]\n 그러니까 3이랑 4의 인덱스는 [1,1]이다! 이런 뜻이야~\n '

In [ ]:
#max 혹은 argmax만 리턴받고 싶을 때
print('Max : ', t7.max(dim=0)[0])
print('Agrmax : ', t7.max(dim=0)[1])

In [ ]:
#dim=1로 인자를 주었을 때 & dim=-1로 인자를 주었을 때
print(t7.max(dim=1))
print(t7.max(dim=-1))