<a href="https://colab.research.google.com/github/ehho34/PyTorch/blob/main/03_%EC%84%A0%ED%98%95%ED%9A%8C%EA%B7%80_1(Linear_Regression).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**03.선형회귀(Linear Regression)**

##**01-선형 회귀**

###**데이터에 대한 이해(Data Definition)**

In [ ]:
"""
-예측을 위해 사용하는 데이터 == 훈련 데이터셋(training dataset)
-학습이 끝난 후에 이 모델이 얼마나 잘 작동하는지 판별 == 테스트 데이터셋(test dataset)

-훈련 데이터셋의 구성
  -모델을 학습시키기 위한 데이터는 파이토치의 텐서 형태여야 함!
  -입력과 출력은 서로 다른 텐서에 저장해야 함!(입력은 x, 출력은 y)<-보편적으로~
  EX) 공부시간과 점수(아래 사진 참고)
  x_train = torch.FloatTensor([[1],[2],[3]])
  y_train = torch.FloatTensor([[2],[4],[6]])

-가설(Hypothesis) 수립
  -머신 러닝에서 식을 세울 때 이 식을 가설이라고 함

-선형 회귀
 -이 가설은 널리 알려져 있으니까 고민 불필요
 -선형 회귀란? : 학습 데이터와 가장 잘 맞는 하나의 직선을 찾는 일
                 일반적으로 이런 식     y = Wx + b 
                                     H(x) = Wx + b 을 가진다 (가설의 H를 따서 y대신 쓴 것뿐임)
                                     -여기서 x와 곱해지는 W를 가중치(Weight)라고 하며, b를 편향(bias)라고 함
                                     -W와 b는 중학교 수학 과정 직선의 방정식에서 기울기와 y절편에 해당
"""

In [ ]:
"""
-비용 함수(Cost Function)에 대한 이해
=손실 함수(loss function)=오차 함수(error function)=목적 함수(objective function)
★ 특히 비용 함수, 손실 함수 기억해두기 ★

-(실제값-예측값)의 제곱을 다 더하고 데이터의 개수로 나눈 것! -> 평균 제곱 오차(Mean Squared Error, MSE)
-Cost(W,b)를 최소로 만드는 W와 b를 구하면 훈련 데이터를 가장 잘 나타내는 직선을 구할 수 있다!
"""

In [ ]:
"""
-옵티마이저 - 경사 하강법(Gradient Descent)
-기울기가 지나치게 크면 실제값과 예측값의 오차가 커기고 기울기가 지나치게 작아도 마찬가지
-사실 b 또한 위와 같음

-cost가 최소화 되는 지점은 접선의 기울기가 0이 되는 지점 = 미분값이 0이 되는 지점
"""

###**파이토치로 선형 회귀 구현하기**

####**1.기본 셋팅**

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [ ]:
#현재 실습하고 있는 코드를 다시 실행해도 다음에도 같은 결과가 나올 수 있게 랜덤 시들들 줄이기
torch.manual_seed(1)

####**2.변수 선언**

In [ ]:
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

In [ ]:
print(x_train)
print(x_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [ ]:
print(y_train)
print(y_train.shape)

tensor([[2.],
        [4.],
        [6.]])
torch.Size([3, 1])


####**3.가중치와 편향의 기초화**

In [ ]:
#가중치 W를 0으로 초기화하고 학습을 통해 값이 변경되는 변수임을 명시함.
W = torch.zeros(1, requires_grad=True)  #requires_grad=True <- '이 변수는 학습을 통해 계속 값이 변경되는 변수임'
#가중치 W를 출력
print(W)

tensor([0.], requires_grad=True)


In [ ]:
#편향 b를 0으로 초기화하고 얘도 학습을 통해 값이 변경되는 변수임을 명시하자!
b = torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)


In [ ]:
#W와 b의 값이 모두 0이기 때문에 현재 이 직선의 방정식은 y = 0 X x + 0 --> x에 어떤 수가 들어가더라도 가설은 0을 예측할 것임!

####**4.가설 세우기**
H(x) = Wx + b

In [ ]:
hypothesis = x_train * W + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


####**5.비용 함수 선언하기**

In [ ]:
#평균 구하기(torch.mean 사용)
cost = torch.mean((hypothesis - y_train) ** 2)
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


####**6.경사 하강법 구현하기**


In [ ]:
optimizer = optim.SGD([W,b],lr=0.01)  #SDG(경사 하강법의 일종), lr(learning rate, 학습률)

In [ ]:
#미분을 통해 얻은 기울기를 0으로 초기화(기울기를 초기화해야지 새로운 가중치 편향에 대해서 새로운 기울기를 구할 수 있다.)
#gradient를 0으로 초기화
optimizer.zero_grad()
#비용 함수를 미분하여 gradient 계산 
cost.backward() #이 함수를 호출하면 인수로 들어갔던 W와 b에서 리턴되는 변수들의 기울기에 학습률(learning rate) 0.01을 곱하여 빼줌으로서 업데이트

####**7.전체 코드**

In [ ]:
#데이터
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

#모델 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

#optimizer 설정
optimizer = optim.SGD([W,b], lr=0.01)

nb_epochs = 1999 #원하는만큼 경사 하강법을 반복
for epoch in range(nb_epochs + 1):

  #H(x) 계산
  hypothesis = x_train * W + b

  #cost 계산
  cost = torch.mean((hypothesis - y_train) ** 2)

  #cost로 H(x) 개선
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  #100번마다 로그 출력
  if epoch % 100 ==0:
    print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
        epoch, nb_epochs, W.item(), b.item(), cost.item()
,     ))

Epoch    0/1999 W: 0.187, b: 0.080 Cost: 18.666666
Epoch  100/1999 W: 1.746, b: 0.578 Cost: 0.048171
Epoch  200/1999 W: 1.800, b: 0.454 Cost: 0.029767
Epoch  300/1999 W: 1.843, b: 0.357 Cost: 0.018394
Epoch  400/1999 W: 1.876, b: 0.281 Cost: 0.011366
Epoch  500/1999 W: 1.903, b: 0.221 Cost: 0.007024
Epoch  600/1999 W: 1.924, b: 0.174 Cost: 0.004340
Epoch  700/1999 W: 1.940, b: 0.136 Cost: 0.002682
Epoch  800/1999 W: 1.953, b: 0.107 Cost: 0.001657
Epoch  900/1999 W: 1.963, b: 0.084 Cost: 0.001024
Epoch 1000/1999 W: 1.971, b: 0.066 Cost: 0.000633
Epoch 1100/1999 W: 1.977, b: 0.052 Cost: 0.000391
Epoch 1200/1999 W: 1.982, b: 0.041 Cost: 0.000242
Epoch 1300/1999 W: 1.986, b: 0.032 Cost: 0.000149
Epoch 1400/1999 W: 1.989, b: 0.025 Cost: 0.000092
Epoch 1500/1999 W: 1.991, b: 0.020 Cost: 0.000057
Epoch 1600/1999 W: 1.993, b: 0.016 Cost: 0.000035
Epoch 1700/1999 W: 1.995, b: 0.012 Cost: 0.000022
Epoch 1800/1999 W: 1.996, b: 0.010 Cost: 0.000013
Epoch 1900/1999 W: 1.997, b: 0.008 Cost: 0.000008

###**optimizer.zero_grad()가 필요한 이유**

In [ ]:
#파이토치는 미분을 통해 얻은 기울기를 이전에 계산된 기울기 값에 누적시키는 특징이 있습니다.

In [ ]:
import torch
w = torch.tensor(2.0, requires_grad=True)

nb_epochs = 20
for epoch in range(nb_epochs + 1):

  z =2*w

  z.backward()
  print('수식을 w로 미분한 값 : {}'.format(w.grad))

수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 4.0
수식을 w로 미분한 값 : 6.0
수식을 w로 미분한 값 : 8.0
수식을 w로 미분한 값 : 10.0
수식을 w로 미분한 값 : 12.0
수식을 w로 미분한 값 : 14.0
수식을 w로 미분한 값 : 16.0
수식을 w로 미분한 값 : 18.0
수식을 w로 미분한 값 : 20.0
수식을 w로 미분한 값 : 22.0
수식을 w로 미분한 값 : 24.0
수식을 w로 미분한 값 : 26.0
수식을 w로 미분한 값 : 28.0
수식을 w로 미분한 값 : 30.0
수식을 w로 미분한 값 : 32.0
수식을 w로 미분한 값 : 34.0
수식을 w로 미분한 값 : 36.0
수식을 w로 미분한 값 : 38.0
수식을 w로 미분한 값 : 40.0
수식을 w로 미분한 값 : 42.0


###**torch.manual_seed()를 하는 이유**

In [ ]:
#torch.manual_seed()를 사용한 프로그램의 결과는 다른 컴퓨터에서 실행시켜도 동일한 결과를 낸다.
#torch.manual_seed()는 난수 발생 순서와 값을 동일하게 보장해주는 특징을 갖고 있기 때문이다!

In [ ]:
import torch

In [ ]:
torch.manual_seed(3) #랜덤시드가 3
print('랜덤 시드가 3일 때')
for i in range(1,3):
  print(torch.rand(1))
#랜덤시드가 3일 때 난수 2개를 발생시켰더니 0.0043과 0.1056이 나옴  

랜덤 시드가 3일 때
tensor([0.0043])
tensor([0.1056])


In [ ]:
torch.manual_seed(5)
print('랜덤 시드가 5일 때')
for i in range(1,3):
  print(torch.rand(1))

랜덤 시드가 5일 때
tensor([0.8303])
tensor([0.1261])


In [ ]:
#다시 랜덤 시드값을 처음에 한 것처럼 3으로 돌려보자! 그럼 어떻게 될까?
torch.manual_seed(3)
print('랜덤 시드가 3일 때')
for i in range(1,3):
  print(torch.rand(1))
  #동일한 값 도출

랜덤 시드가 3일 때
tensor([0.0043])
tensor([0.1056])


In [ ]:
#tersor에는 requires_grab라는 속성이 있는데, requires+grab=True로 설정하면 자동 미분 기능이 적용된다.
#이렇게 설정된 텐서에서 연산을 하면 계산 그래프가 생성됨. backward 함수를 호출하면 그래프로부터 자동으로 미분이 계산된다! 

##**02.자동 미분(Autograd)**

###1.경사 하강법 리뷰

In [7]:
#경사 하강법 : 비용함수를 미분 -> 이함수의 기울기를 구하여 비용이 최소화 되는 방향을 찾아내는 알고리즘
#비용함수=손실함수=오차함수
#비용(=손실=오차)을 최소화 되는 방향

###**2.자동 미분(Autograb) 실습하기**

In [8]:
#모델이 복잡해지면 직접 코딩하기 까다롭잖아? 그러니까 자동미분으로 미분 계산을 자동화 하자~
import torch

In [10]:
#값이 2인 임의의 스칼라 텐서 w를 생성
w = torch.tensor(2.0, requires_grad=True) #'requires_grad=True'==이 텐서에 대한 기울기를 저장하겠다!

In [11]:
#수식 정의
y = w**2
z = 2*y +5

In [12]:
#수식을 w에 대해서 미분하기!
z.backward()  #.backward()를 호출하면 해당 수식의 w에 대한 기울기를 계산함

In [14]:
#w.grad 출력
print('수식을 w로 미분한 값 : {}'.format(w.grad))

수식을 w로 미분한 값 : 8.0


##**03. 다중 선형 회귀(Multivariable Linear regression)**
#####*x가* 1개인 선형 회귀를 단순 선형회귀라고 함. 다중 선형 회귀는 다수의 x로부터 y를 예측하는 것!

###**2.파이토치로 구현하기**

In [4]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [ ]:
torch.maanual_seed(1) #랜덤시드 고정

In [20]:
#H(x) = w1x1 + w2x2 +w3x3 + b
#이번 데이터는 단순 선형 회귀와 달리 x의 개수가 3개!
# 훈련 데이터(x가 3개 선언)
x1_train = torch.FloatTensor([[73], [93], [89], [96], [73]])
x2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
x3_train = torch.FloatTensor([[75], [93], [90], [100], [70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [18]:
# 가중치 w와 편향 b 선언(x가 3개니까 가중치 w도 3개 선언)
w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [19]:
#가설, 비용함수, 옵티마이저 선언
# optimizer 설정
optimizer = optim.SGD([w1, w2, w3, b], lr=1e-5)

nb_epochs = 1000 #경사 하강법 1000회 반복
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = x1_train * w1 + x2_train * w2 + x3_train * w3 + b  #가설을 서너
    # ▲가설을 선언하는 이부분도 x_train의 개수만큼 w와 곱해주도록 작성!
    
    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} w1: {:.3f} w2: {:.3f} w3: {:.3f} b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, w1.item(), w2.item(), w3.item(), b.item(), cost.item()
        ))

Epoch    0/1000 w1: 0.294 w2: 0.294 w3: 0.297 b: 0.003 Cost: 29661.800781
Epoch  100/1000 w1: 0.674 w2: 0.661 w3: 0.676 b: 0.008 Cost: 1.563628
Epoch  200/1000 w1: 0.679 w2: 0.655 w3: 0.677 b: 0.008 Cost: 1.497595
Epoch  300/1000 w1: 0.684 w2: 0.649 w3: 0.677 b: 0.008 Cost: 1.435044
Epoch  400/1000 w1: 0.689 w2: 0.643 w3: 0.678 b: 0.008 Cost: 1.375726
Epoch  500/1000 w1: 0.694 w2: 0.638 w3: 0.678 b: 0.009 Cost: 1.319507
Epoch  600/1000 w1: 0.699 w2: 0.633 w3: 0.679 b: 0.009 Cost: 1.266222
Epoch  700/1000 w1: 0.704 w2: 0.627 w3: 0.679 b: 0.009 Cost: 1.215703
Epoch  800/1000 w1: 0.709 w2: 0.622 w3: 0.679 b: 0.009 Cost: 1.167810
Epoch  900/1000 w1: 0.713 w2: 0.617 w3: 0.680 b: 0.009 Cost: 1.122429
Epoch 1000/1000 w1: 0.718 w2: 0.613 w3: 0.680 b: 0.009 Cost: 1.079390


###**3.벡터와 행렬 연산으로 바꾸기**
#####위의 코드 같은 경우에는 x가 3개니까 일일히 선언하는 게 가능! 근데 x가 1000개라면..? -> 너무 비효율적!
#####이걸 해결하기 위해서 -> 행렬 곱셈 연산(벡터의 내적=Odt Product)을 사용하자!

####**벡터 연산으로 이해하기**

In [ ]:
'''
H(X) = w1x1 + w2x2 + w3x3
두 벡터의 내적으로 표현하면 -> H(X) = XW
'''

####**행렬 연산으로 이해하기**
#####샘플 (sample) : 전체 훈련 데이터의 개수를 셀 수 있는 1개의 단위
#####특성(feature) : 각 샘플에서 y를 결정하게 하는 각각의 독립 변수 x
#####독립변수 x들의 수 = 샘플의 수 x 특성의 수

####**행렬 연산을 고려하여 파이토치로 구현하기**

In [5]:
#행렬 연산을 고려하여 파이토치로 재구현 <- 훈련 데이터도 행렬로 선언해주어야 함
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  80], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

In [6]:
print(x_train.shape)
print(y_train.shape)

torch.Size([5, 3])
torch.Size([5, 1])


In [8]:
#가중치와 편향 선언
W = torch.zeros((3,1), requires_grad=True) 
#행렬의 곱셉이 성립되려면 좌측에 있는 행렬과 우측에 있는 행렬 크기가 같아아 햠
#X_train(5X3), W벡터의 크기(3X1)이므로 행렬곱 가능!

b = torch.zeros(1, requires_grad=True)

In [9]:
#가설 선언
hypothesis = x_train.matmul(W) + b

In [10]:
#전체 코드
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  80], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

# 모델 초기화
W = torch.zeros((3, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

# optimizer 설정
optimizer = optim.SGD([W, b], lr=1e-5)

nb_epochs = 20
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    # 편향 b는 브로드 캐스팅되어 각 샘플에 더해집니다.
    hypothesis = x_train.matmul(W) + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(
        epoch, nb_epochs, hypothesis.squeeze().detach(), cost.item()
    ))

Epoch    0/20 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch    1/20 hypothesis: tensor([66.7178, 80.1701, 76.1025, 86.0194, 61.1565]) Cost: 9537.694336
Epoch    2/20 hypothesis: tensor([104.5421, 125.6208, 119.2478, 134.7862,  95.8280]) Cost: 3069.590088
Epoch    3/20 hypothesis: tensor([125.9858, 151.3882, 143.7087, 162.4333, 115.4844]) Cost: 990.670288
Epoch    4/20 hypothesis: tensor([138.1429, 165.9963, 157.5768, 178.1071, 126.6283]) Cost: 322.481873
Epoch    5/20 hypothesis: tensor([145.0350, 174.2780, 165.4395, 186.9928, 132.9461]) Cost: 107.717064
Epoch    6/20 hypothesis: tensor([148.9423, 178.9730, 169.8976, 192.0301, 136.5279]) Cost: 38.687496
Epoch    7/20 hypothesis: tensor([151.1574, 181.6346, 172.4254, 194.8856, 138.5585]) Cost: 16.499043
Epoch    8/20 hypothesis: tensor([152.4131, 183.1435, 173.8590, 196.5043, 139.7097]) Cost: 9.365656
Epoch    9/20 hypothesis: tensor([153.1250, 183.9988, 174.6723, 197.4217, 140.3625]) Cost: 7.071114
Epoch   10/20 hyp